#! /bin/bash
PREV_BL_VAL=/tmp/prev_backlight_value 
BACKLIGHT=$(xbacklight|cut -d . -f 1)

if [ $BACKLIGHT -le 15 ];
then
    if [ $BACKLIGHT -le 6 ];
    then
        STEP=1
    else
        STEP=2
    fi
else
    STEP=10
fi

if [ "$1" == "up" ];
then
    xbacklight +$STEP
elif [ "$1" == "down" ];
then
    xbacklight -$STEP
elif [ "$1" == "toggle" ];
then
    if [ $BACKLIGHT -eq 0 ];
    then
        if [ -e $PREV_BL_VAL ];
        then
            BACKLIGHT=$(cat $PREV_BL_VAL)
            xbacklight =$BACKLIGHT
        else
            xbacklight =50
        fi
    else
        echo $BACKLIGHT > $PREV_BL_VAL
        xbacklight =0
    fi
fi
